### ISSUE TITLE
Getting bluebird error

### ISSUE THREAD

**Issue by winkler1** [khanghoang/RNSideMenu#4]
Hi-
 Getting this in react packager, have you seen this before?

module.js:338
    throw err;
          ^
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Jeff/repos/ghtemp/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:13:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
Process terminated. Press <enter> to close the window

**Comment by khanghoang** [comment]
@winkler1 never before, can you show me how to reproduce it?

**Comment by khanghoang** [comment]
@winkler1 after cloning it, i can see that error

**Comment by khanghoang** [comment]
@winkler1 okie, i think it's because node version collision, first step remove the "node_modules" folder, then run `npm install`, note that I use node version `0.1.12`

**Comment by khanghoang** [comment]
@winkler1 I have separated examples into another [repo](https://github.com/khanghoang/RNSideView-Examples), so for now on this repo just contains nom files.
